name = "repo-proxy"
main = "workers/repo-proxy.ts"
compatibility_date = "2024-01-01"

[[r1_buckets]]
binding = "R2_BUCKET"
bucket_name = "bluefin"

routes = [
  { pattern = "repo.tuna-os.dev/*", zone_name = "tuna-os.dev" }
]

[vars]
ENV = "production"
