name = "repo-proxy"
main = "workers/repo-proxy.ts"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "repo.tunaos.org/*", zone_name = "tunaos.org" }
]

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "bluefin"

[vars]
ENV = "production"
